import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import { Header } from "@/components/Header";
import { TransactionsProvider } from "@/contexts/TransactionsContext";

import "@/styles/global.scss";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ticto | Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      className={roboto.className}
    >
      <body>
        <TransactionsProvider>{children}</TransactionsProvider>
      </body>
    </html>
  );
}
